### PR TITLE
Add undeclared dependency on 'future'.

### PR DESCRIPTION
**Pull request by tisto**
This pull request includes a

- [ ] An improvement
- [X] Bug fix
- [ ] New feature

The following changes were made

- Add undeclared dependency on 'future'.

### CODE REVIEW

**Comment by tisto** [comment]
Installing robotframework-djangolibrary on a fresh virtualenv fails because there is an undeclared dependency on "future".

> pip install -U https://github.com/HelioGuilherme66/robotframework-selenium2library/archive/v1.8.0b1.tar.gz

Running "pip install future" up front fixes the issue. See

> https://github.com/kitconcept/robotframework-djangolibrary/blob/master/.travis.yml#L15

**Comment by HelioGuilherme66** [comment]
Thanks for the PR.
However, it was set to 'master', but the tag v1.8.0b1 is based on the branch 'code_futurized'. This branch already contains the change you propose.
I will produce a new package to avoid the virtualenv errors.

**Comment by HelioGuilherme66** [comment]
You may try to install https://github.com/HelioGuilherme66/robotframework-selenium2library/releases/tag/v1.8.0b2

**Comment by tisto** [comment]
@HelioGuilherme66 thanks for the quick response! The 1.8.0b2 release link is not working. Though, 1.8.0b3 works like a charm! 

https://github.com/kitconcept/robotframework-djangolibrary/pull/15/files

**Pull request closed without merging**
